/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_pendaftaran;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author TOSHIBA
 */
public class Kartu_tes extends javax.swing.JFrame {
private Connection conec;

private net.sf.jasperreports.engine.design.JasperDesign Jasper_Design;
    private JasperReport Jasper_Report;
    private Map<String, Object> Parameter = new HashMap<String, Object>();
    private JasperPrint Jasper_Print;

    /**
     * Creates new form Kartu_Tes
     */
private void tabs(){
        String sql="select * from tblkartu";
        DefaultTableModel ax=new DefaultTableModel();
        ax.addColumn("ID_Kartu");
        ax.addColumn("ID_Pendaftar");
        ax.addColumn("Nama_Lengkap");
        ax.addColumn("Ruang_Tes");
        ax.addColumn("Waktu");
        ax.addColumn("Jam");
        
        tblkartutes.setModel(ax);
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                
                ax.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
                System.out.println("koneksi sukses");

        }

        }
        catch(Exception e){
            System.out.println("Err koneksi gagal");
        }   
}

    public Kartu_tes() {
        initComponents();
        koneksiDatabase();
        //cbidsiswa();
        nomoran();
        tabs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cbjenkel = new javax.swing.JComboBox();
        tfidsiswa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tftempatlahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tftanggal = new javax.swing.JTextField();
        tfnotelp = new javax.swing.JTextField();
        tblsave = new javax.swing.JButton();
        tblsearch = new javax.swing.JButton();
        tbledit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbldelete = new javax.swing.JButton();
        tfnamasiswa = new javax.swing.JTextField();
        tblcancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfalamat = new javax.swing.JTextArea();
        aa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfidkartu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfviewnotelp = new javax.swing.JTextField();
        tblsave1 = new javax.swing.JButton();
        tblsearch1 = new javax.swing.JButton();
        tbledit1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tbldelete1 = new javax.swing.JButton();
        tfviewnama = new javax.swing.JTextField();
        tblcancel1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfviewalamat = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfwaktu = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfjam = new javax.swing.JTextField();
        tfviewjurusan = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfruang = new javax.swing.JTextField();
        tfidpendaftar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblkartutes = new javax.swing.JTable();
        tblprint = new javax.swing.JButton();
        tfidprint = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        jLabel8.setText(":");

        cbjenkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":: Pilih Jenis Kelamin ::", "Laki-laki", "Perempuan" }));

        jLabel11.setText(":");

        jLabel7.setText(":");

        jLabel6.setText(" No_telp");

        jLabel5.setText("Tanggal_Lahir");

        jLabel4.setText("Tempat_Lahir");

        jLabel15.setText(":");

        tblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave.setText("Save");

        tblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch.setText("Search");

        tbledit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        tbledit.setText("Edit");

        jLabel2.setText("ID_Siswa");

        jLabel9.setText(":");

        jLabel3.setText("Nama_Siswa");

        jLabel10.setText(":");

        tbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete16.gif"))); // NOI18N
        tbldelete.setText("Delete");

        tblcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel.setText("Cancel");

        jLabel12.setText("Alamat");

        jLabel13.setText(":");

        jLabel14.setText("Jenis_Kelamin");

        tfalamat.setColumns(20);
        tfalamat.setRows(5);
        jScrollPane1.setViewportView(tfalamat);

        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KARTU PESERTA TES");

        jLabel17.setText(":");

        jLabel18.setText(":");

        jLabel19.setText(" No_telp");

        tblsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave1.setText("Save");
        tblsave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsave1ActionPerformed(evt);
            }
        });

        tblsearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch1.setText("Search");
        tblsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsearch1ActionPerformed(evt);
            }
        });

        tbledit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        tbledit1.setText("Edit");
        tbledit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbledit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbledit1ActionPerformed(evt);
            }
        });

        jLabel23.setText("ID_Pendaftar");

        tbldelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete16.gif"))); // NOI18N
        tbldelete1.setText("Delete");
        tbldelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbldelete1ActionPerformed(evt);
            }
        });

        tfviewnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfviewnamaActionPerformed(evt);
            }
        });

        tblcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel1.setText("Cancel");
        tblcancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancel1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Alamat");

        jLabel28.setText(":");

        tfviewalamat.setColumns(20);
        tfviewalamat.setRows(5);
        jScrollPane2.setViewportView(tfviewalamat);

        jLabel20.setText("Jurusan");

        jLabel21.setText("Ruang_tes");

        jLabel22.setText("Waktu");

        jLabel24.setText(":");

        jLabel26.setText(":");

        jLabel29.setText(":");

        jLabel31.setText("Jam");

        jLabel32.setText(":");

        jLabel33.setText("ID_Kartu");

        jLabel34.setText(":");

        tfruang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfruang.setText("AULA LANTAI 1");
        tfruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfruangActionPerformed(evt);
            }
        });

        tfidpendaftar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidpendaftarKeyPressed(evt);
            }
        });

        jLabel16.setText("WIB");

        tblkartutes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblkartutes);

        tblprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        tblprint.setText("Print");
        tblprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblprintActionPerformed(evt);
            }
        });

        jLabel35.setText(":");

        jLabel36.setText("ID_Kartu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfidkartu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tblsearch1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel27)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfviewjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfjam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfidpendaftar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(106, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tblsave1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbledit1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbldelete1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tblcancel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel19)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfviewnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfidprint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel36))
                                        .addGap(18, 18, 18)
                                        .addComponent(tblprint)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tblsearch1)
                    .addComponent(jLabel34)
                    .addComponent(tfidkartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel18)
                    .addComponent(tfidpendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24)
                            .addComponent(tfviewjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel17))
                            .addComponent(tfviewnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(tfruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel29)
                            .addComponent(tfwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(tfjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblsave1)
                            .addComponent(tbledit1)
                            .addComponent(tbldelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblcancel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35)
                    .addComponent(tfidprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblprint))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-951)/2, (screenSize.height-607)/2, 951, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void tblsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsave1ActionPerformed
        // TODO add your handling code here:
        String vidk       = tfidkartu.getText();
        //String vnama     = tfviewnama.getText();
        String vid       = tfidpendaftar.getText();
        //String valamat   = tfviewalamat.getText();
        //String vtelp     = tfviewnotelp.getText();
        String vjurusan  = tfviewjurusan.getText();
        String vruang    = tfruang.getText();
        String vwaktu    = tfwaktu.getText();
        String vjam      = tfjam.getText();
        String  vnama   = tfviewnama.getText();
        if (tfidkartu.getText().trim().equals("")){
          JOptionPane.showMessageDialog(null,"Data Masih Kosong",
                "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                java.sql.Statement stat=conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT * FROM tblkartu WHERE ID_Kartu='"+tfidkartu.getText()+"'");
                if (data.next()){
                    JOptionPane.showMessageDialog(null,"ID Kartu sudah dimasukkan");
                    tfidpendaftar.requestFocus();
                }
                else {
                    String sql = "INSERT INTO tblkartu VALUES('"+vidk+"','"+vid+"','"+vnama+"','"+vjurusan+"','"+vruang+"','"+vwaktu+"','"+vjam+"')";
                    stat.executeUpdate(sql);
                    tfidkartu.setText("");
                    tfidpendaftar.setText("");
                    tfviewnama.setText("");
                    tfviewalamat.setText("");
                    tfviewnotelp.setText("");
                    tfviewjurusan.setText("");
                    //tfruang.setText("");
                    tfwaktu.setText("");
                    tfjam.setText("");
                    tfidkartu.requestFocus();
                }
                nomoran();
                //cbidsiswa();
                stat.close();
            }
            catch (Exception exc){
                System.err.println("Terjadi Kesalahan :"+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tblsave1ActionPerformed

    private void tblsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsearch1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM tblkartu WHERE ID_Kartu='"+tfidkartu.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfidpendaftar.setText(rs.getString(2));                
                tfwaktu.setText(rs.getString(4));
                tfjam.setText(rs.getString(5));
                String vid      = tfidpendaftar.getText();
                String sql2 = "SELECT * FROM tblpendaftar WHERE ID_Pendaftar='"+vid+"'";
                try{
                    Statement stat2=conec.createStatement();
                    ResultSet rs2=stat2.executeQuery(sql2);
                    if(rs2.next())
                    {
                        tfviewnama.setText(rs2.getString(2));
                        tfviewalamat.setText(rs2.getString(7));
                        tfviewnotelp.setText(rs2.getString(8));
                        tfviewjurusan.setText(rs2.getString(9));
                    }
                }
                catch(Exception exc){
                System.err.println("Terjadi kesalahan : "+exc);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
               tfidkartu.requestFocus();
            }
          stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
    }//GEN-LAST:event_tblsearch1ActionPerformed

    private void tbledit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbledit1ActionPerformed
        // TODO add your handling code here:
        String sql="update tblkartu set ID_Pendaftar='"+tfidpendaftar.getText()+"',Ruang_tes='"+tfruang.getText()+"',Waktu='"+tfwaktu.getText()+"',Jam='"+tfjam.getText()+"'where ID_Kartu='"+tfidkartu.getText().trim()+"'";
        if(tfidkartu.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data masih kosong !","Edit Data",JOptionPane.WARNING_MESSAGE);
            tfidkartu.requestFocus();
        }
        else {
            try {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data sudah di edit","Edit Data",JOptionPane.WARNING_MESSAGE);
                stat.close();
                //conec.close();
                tfidpendaftar.setText("");
                tfviewnama.setText("");
                tfviewalamat.setText("");
                tfviewnotelp.setText("");
                tfviewjurusan.setText("");
                tfwaktu.setText("");
                tfjam.setText("");
                tfidkartu.requestFocus();

                nomoran();
                stat.close();

            }
            catch (Exception exc) {
                System.err.println("Error : "+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbledit1ActionPerformed

    private void tbldelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbldelete1ActionPerformed
        // TODO add your handling code here:
        String sql="delete from tblkartu where ID_Kartu='"+tfidkartu.getText().trim()+"'";
        if(tfidkartu.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "kode masih kosong !","Hapus Data",JOptionPane.WARNING_MESSAGE);
            tfidkartu.requestFocus();
        }
        else
        {
            try
            {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data sudah dihapus","Hapus Data",JOptionPane.WARNING_MESSAGE);
                stat.close();
                tfidkartu.setText("");
                tfidpendaftar.setText("");
                tfviewnama.setText("");
                tfviewalamat.setText("");
                tfviewnotelp.setText("");
                tfviewjurusan.setText("");
                //tfruang.setText("");
                tfwaktu.setText("");
                tfjam.setText("");
                tfidkartu.requestFocus();

                nomoran();
            }
            catch(Exception exc)
            {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbldelete1ActionPerformed

    private void tfviewnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfviewnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfviewnamaActionPerformed

    private void tblcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancel1ActionPerformed

    private void tfidpendaftarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidpendaftarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            aaActionPerformed(new ActionEvent(evt.getSource(),evt.getID(),"KEY PRESS PROCESS"));
        }
    }//GEN-LAST:event_tfidpendaftarKeyPressed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM tblpendaftar WHERE ID_Pendaftar='"+tfidpendaftar.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfviewnama.setText(rs.getString(2));
                tfviewalamat.setText(rs.getString(7));
                tfviewnotelp.setText(rs.getString(8));
                tfviewjurusan.setText(rs.getString(9));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfidsiswa.requestFocus();
            }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
    }//GEN-LAST:event_aaActionPerformed

    private void tfruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfruangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfruangActionPerformed

    private void tblprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblprintActionPerformed
        // TODO add your handling code here:
        try{
         String report ="src/report/kartutes.jrxml";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conec = DriverManager.getConnection("jdbc:mysql://localhost/sistempendaftaran","root","");
            @SuppressWarnings("rawtypes")
            HashMap hash = new HashMap();
            hash.put("ID_Kartu", tfidprint.getText());
            
            File file = new File(report);
//            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file);
            Jasper_Design = JRXmlLoader.load(report);
            Jasper_Report = JasperCompileManager.compileReport(Jasper_Design);
            JasperPrint jasperPrint = JasperFillManager.fillReport(Jasper_Report, hash, conec);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tblprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kartu_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kartu_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kartu_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kartu_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kartu_tes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aa;
    private javax.swing.JComboBox cbjenkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton tblcancel;
    private javax.swing.JButton tblcancel1;
    private javax.swing.JButton tbldelete;
    private javax.swing.JButton tbldelete1;
    private javax.swing.JButton tbledit;
    private javax.swing.JButton tbledit1;
    private javax.swing.JTable tblkartutes;
    private javax.swing.JButton tblprint;
    private javax.swing.JButton tblsave;
    private javax.swing.JButton tblsave1;
    private javax.swing.JButton tblsearch;
    private javax.swing.JButton tblsearch1;
    private javax.swing.JTextArea tfalamat;
    private javax.swing.JTextField tfidkartu;
    private javax.swing.JTextField tfidpendaftar;
    private javax.swing.JTextField tfidprint;
    private javax.swing.JTextField tfidsiswa;
    private javax.swing.JTextField tfjam;
    private javax.swing.JTextField tfnamasiswa;
    private javax.swing.JTextField tfnotelp;
    private javax.swing.JTextField tfruang;
    private javax.swing.JTextField tftanggal;
    private javax.swing.JTextField tftempatlahir;
    private javax.swing.JTextArea tfviewalamat;
    private javax.swing.JTextField tfviewjurusan;
    private javax.swing.JTextField tfviewnama;
    private javax.swing.JTextField tfviewnotelp;
    private javax.swing.JTextField tfwaktu;
    // End of variables declaration//GEN-END:variables

    private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
        try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistempendaftaran","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
    }

    private void nomoran() {
        //throw new UnsupportedOperationException("Not yet implemented");
                String sql = "select right (ID_Kartu,3) as no from tblkartu order by ID_Kartu asc";
        
        try {
            Statement pst = conec.prepareStatement(sql);
            Statement stat = conec.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            if (rs.first()==false)
            {
                tfidkartu.setText("0001");
            }
            else {
                rs.last();
                int no = rs.getInt(1)+1;
                String kbinasi = String.valueOf(no);
                int pjg_kbinasi = kbinasi.length();
                String jebot = "";
                for(int i=0; i<3-pjg_kbinasi;i++){
                   // kbinasi = "0"+kbinasi;
                    jebot = jebot+"0";
                }
                tfidkartu.setText("0"+jebot+kbinasi);
            }
            rs.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan:"+e);
            
        }
    }
    
/*        private void cbidsiswa() {
        
                {
        String sql="select * from tblpendaftar";
        
        
        try{
           // cbcs.removeAllItems();
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                
                String uu=rs.getString("ID_Siswa");
                cbidsiswa.addItem(uu);
                
        }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
        }
    }
    }*/
}
