/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_pendaftaran;
import java.io.File;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author TOSHIBA
 */
public class Laporan_hasil_tes extends javax.swing.JFrame {
    private Connection conec;
    DefaultTableModel tabModelTransaksi;
       private net.sf.jasperreports.engine.design.JasperDesign Jasper_Design;
    private JasperReport Jasper_Report;
    private Map<String, Object> Parameter = new HashMap<String, Object>();
    private JasperPrint Jasper_Print;
    /**
     * Creates new form Daftar_calon_siswa
     */
    public Laporan_hasil_tes() {
        initComponents();
        koneksiDatabase();
        tampiljurusan();
        Object[] judul_kolom = {"ID Kartu","ID Nilai","Nama Lengkap","Matematika","Bahasa Indonesia","Bahasa Inggris","Rata-Rata","Keterangan"};
        tabModelTransaksi=new DefaultTableModel(null,judul_kolom);
        jTable1.setModel(tabModelTransaksi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbjurusan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tblproses = new javax.swing.JButton();
        cmb_status = new javax.swing.JComboBox();
        tblproses1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jurusan");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbjurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjurusanActionPerformed(evt);
            }
        });

        jLabel2.setText(":");

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HASIL SELEKSI CALON SISWA");

        tblproses.setText("Proses");
        tblproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblprosesActionPerformed(evt);
            }
        });

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":: Pilih ::", "Lulus", "Gagal" }));
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });

        tblproses1.setText("Print");
        tblproses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblproses1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tblproses))
                            .addComponent(cbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(536, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tblproses1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblproses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblproses1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-899)/2, (screenSize.height-395)/2, 899, 395);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void cbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjurusanActionPerformed
//        String sql="select distinct Jurusan from tblpendaftar order by Jurusan asc";
//        try{
//            Statement stat = conec.createStatement();
//            ResultSet rs = stat.executeQuery(sql);
//            if(rs.next()){
//                nm_jurusan.setText(rs.getString("jurusan"));
//            }
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
//        }
    }//GEN-LAST:event_cbjurusanActionPerformed

    private void tblprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblprosesActionPerformed
        tabModelTransaksi.getDataVector().removeAllElements();
        //String sql="select * from tblnilai where ID_Jurusan='"+cbjurusan.getSelectedItem()+"' and Keterangan = '" + cmb_status.getSelectedItem() + "'";
        String sql="select * from tblpendaftar,tblnilai,tblkartu WHERE tblpendaftar.ID_Pendaftar=tblkartu.ID_Pendaftar AND tblkartu.ID_Kartu=tblnilai.ID_Kartu AND tblpendaftar.Jurusan='"+cbjurusan.getSelectedItem()+"' and tblnilai.Keterangan = '" + cmb_status.getSelectedItem() + "'";
        try{
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);                
            rs.beforeFirst();
            while(rs.next()){
            String vid_kartu=rs.getString("ID_Kartu");
            String vid_nilai=rs.getString("ID_Nilai");
            String vnama_lengkap=rs.getString("Nama_Lengkap");
            //String vnm_siswa="";
            /*String sql2="select * from tblpendaftar where  ID_Siswa='"+vid_siswa+"'";
            try{
                Statement stat2 = conec.createStatement();
                ResultSet rs2 = stat2.executeQuery(sql2);
                if(rs2.next()){
                    vnm_siswa=rs2.getString("Nama_Siswa");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
            }   */
            String vmatematika=rs.getString("Matematika");
            String vbhsind=rs.getString("B_Indonesia");
            String vbhsing=rs.getString("B_Inggris");
            String vrata=rs.getString("Rata_rata");
            String vket=rs.getString("Keterangan");

            Object[] data={vid_kartu,vid_nilai,vnama_lengkap,vmatematika,vbhsind,vbhsing,vrata,vket};
            tabModelTransaksi.addRow(data);
//            tabModelTransaksi.getDataVector().removeAllElements();
            }
//            if(!rs.next()){
//                Object[] judul_kolom = {"No Peserta","Nama Siswa","Matematika","Bahasa Indonesia","Bahasa Inggris","Rata-Rata","Keterangan"};
//                tabModelTransaksi=new DefaultTableModel(null,judul_kolom);
//                jTable1.setModel(tabModelTransaksi);
//                JOptionPane.showMessageDialog(null,"Data tidak ada");
//            }
        }          
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
        }     
    }//GEN-LAST:event_tblprosesActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void tblproses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblproses1ActionPerformed
        // TODO add your handling code here:
        try{
         String report ="src/report/reporthasiltes.jrxml";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conec = DriverManager.getConnection("jdbc:mysql://localhost/sistempendaftaran","root","");
            @SuppressWarnings("rawtypes")
            HashMap hash = new HashMap();
            hash.put("Jurusan", cbjurusan.getSelectedItem());
            
            File file = new File(report);
//            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            Jasper_Design = JRXmlLoader.load(report);
            Jasper_Report = JasperCompileManager.compileReport(Jasper_Design);
            JasperPrint jasperPrint = JasperFillManager.fillReport(Jasper_Report, hash, conec);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tblproses1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_hasil_tes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbjurusan;
    private javax.swing.JComboBox cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tblproses;
    private javax.swing.JButton tblproses1;
    // End of variables declaration//GEN-END:variables
private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
              try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistempendaftaran","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
  
    }

    private void tampiljurusan() {
        //throw new UnsupportedOperationException("Not yet implemented");
                String sql = "select distinct Jurusan from tblpendaftar order by Jurusan asc";
        
        try{
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                
                String row=rs.getString(1);
                cbjurusan.addItem(row);
                
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan:"+e);
        }

    }

}
