/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_pendaftaran;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TOSHIBA
 */
public class Nilai_hasil_tes extends javax.swing.JFrame {
private Connection conec;
    /**
     * Creates new form Nilai_hasil_tes
     */
private void tabs(){
        String sql="select * from tblnilai";
        DefaultTableModel ax=new DefaultTableModel();
        ax.addColumn("ID_Nilai");
        ax.addColumn("ID_Kartu");
        ax.addColumn("Nama_Lengkap");
        ax.addColumn("jurusan");
        ax.addColumn("Matematika");
        ax.addColumn("B_Indonesia");
        ax.addColumn("B_Inggris");
        ax.addColumn("Jumlah");
        ax.addColumn("Rata_rata");
        ax.addColumn("Keterangan");
        
        tblnilai.setModel(ax);
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                
                ax.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
                System.out.println("koneksi sukses");

        }

        }
        catch(Exception e){
            System.out.println("Err koneksi gagal");
        }   
}
    public Nilai_hasil_tes() {
        initComponents();
        koneksiDatabase();
        nomoran();
        tabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tbledit1 = new javax.swing.JButton();
        tblsave1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tfketerangan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfviewnama = new javax.swing.JTextField();
        tbldelete1 = new javax.swing.JButton();
        tblcancel1 = new javax.swing.JButton();
        tfmtk = new javax.swing.JTextField();
        tfbindonesia = new javax.swing.JTextField();
        tfbinggris = new javax.swing.JTextField();
        tblproses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfrata = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfviewjurusan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfidnilai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfviewmtk = new javax.swing.JTextField();
        tfviewbindonesia = new javax.swing.JTextField();
        tfviewbinggris = new javax.swing.JTextField();
        tblsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnilai = new javax.swing.JTable();
        tfidkartu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel21.setText("B. Inggris");

        jLabel22.setText("Jumlah");

        jLabel20.setText("B. Indonesia");

        jLabel19.setText("Matematika");

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("NILAI MATA PELAJARAN");

        jLabel23.setText("Nama");

        tbledit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        tbledit1.setText("Edit");
        tbledit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbledit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbledit1ActionPerformed(evt);
            }
        });

        tblsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SAVE.jpg"))); // NOI18N
        tblsave1.setText("Save");
        tblsave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsave1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NILAI HASIL TES");

        jLabel33.setText("ID_Kartu");

        jLabel34.setText(":");

        tfjumlah.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel31.setText("Keterangan");

        tfketerangan.setEnabled(false);
        tfketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfketeranganActionPerformed(evt);
            }
        });

        jLabel18.setText(":");

        tfviewnama.setEnabled(false);
        tfviewnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfviewnamaActionPerformed(evt);
            }
        });

        tbldelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete16.gif"))); // NOI18N
        tbldelete1.setText("Delete");
        tbldelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbldelete1ActionPerformed(evt);
            }
        });

        tblcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.jpg"))); // NOI18N
        tblcancel1.setText("Cancel");
        tblcancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcancel1ActionPerformed(evt);
            }
        });

        tfmtk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfmtkFocusLost(evt);
            }
        });

        tfbindonesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbindonesiaActionPerformed(evt);
            }
        });
        tfbindonesia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfbindonesiaFocusLost(evt);
            }
        });

        tfbinggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbinggrisActionPerformed(evt);
            }
        });
        tfbinggris.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfbinggrisFocusLost(evt);
            }
        });

        tblproses.setText("Process");
        tblproses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblprosesActionPerformed(evt);
            }
        });

        jLabel2.setText("Rata-rata");

        tfrata.setEnabled(false);

        jLabel4.setText("Jurusan");

        jLabel5.setText(":");

        tfviewjurusan.setEnabled(false);

        jLabel6.setText("ID_Nilai");

        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Nama Materi Test");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Hasil Nilai");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Standard Nilai");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("60");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("60");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("60");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("60");

        tfviewmtk.setEnabled(false);

        tfviewbindonesia.setEnabled(false);

        tfviewbinggris.setEnabled(false);

        tblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchtext.png"))); // NOI18N
        tblsearch.setText("Search");
        tblsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsearchActionPerformed(evt);
            }
        });

        tblnilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblnilai);

        tfidkartu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidkartuKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tblproses)))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(tfrata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(5, 5, 5))
                                                .addComponent(jLabel20))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(108, 108, 108)))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfbinggris, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfbindonesia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel9)
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfviewbinggris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfviewbindonesia)
                                                .addComponent(tfviewmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tfidnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tblsearch)
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel4))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfidkartu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfviewjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(108, Short.MAX_VALUE))))
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tblsave1)
                                .addGap(18, 18, 18)
                                .addComponent(tbledit1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(tbldelete1)
                                .addGap(18, 18, 18)
                                .addComponent(tblcancel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tfidnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblsearch)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(tfidkartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfviewnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfviewjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfmtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfbindonesia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfbinggris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfviewmtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfviewbindonesia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfviewbinggris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblproses)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblsave1)
                    .addComponent(tbledit1)
                    .addComponent(tbldelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblcancel1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-849)/2, (screenSize.height-792)/2, 849, 792);
    }// </editor-fold>//GEN-END:initComponents

    private void tbledit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbledit1ActionPerformed
        // TODO add your handling code here:
        String sql="update tblnilai set Matematika='"+tfmtk.getText()+"',B_Indonesia='"+tfbindonesia.getText()+"',B_Inggris='"+tfbinggris.getText()+"'Jumlah='"+tfjumlah.getText()+"'Rata-rata='"+tfrata.getText()+"'Keterangan='"+tfketerangan.getText()+"'where ID_Nilai='"+tfidnilai.getText()+"'";
        if(tfidnilai.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data masih kosong !","Edit Data",JOptionPane.WARNING_MESSAGE);
            tfidnilai.requestFocus();
        }
        else {
            try {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data sudah di edit","Edit Data",JOptionPane.WARNING_MESSAGE);
                stat.close();
                //conec.close();
                tfviewnama.setText("");
                tfviewjurusan.setText("");
                tfmtk.setText("");
                tfbindonesia.setText("");
                tfbinggris.setText("");
                tfjumlah.setText("");
                tfrata.setText("");
                tfketerangan.setText("");
                tfidnilai.requestFocus();

                stat.close();

            }
            catch (Exception exc) {
                System.err.println("Error : "+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbledit1ActionPerformed

    private void tblsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsave1ActionPerformed
        // TODO add your handling code here:
        String vidn      = (String)tfidnilai.getText();
        String vidk       = (String)tfidkartu.getText();
        String vnama     = tfviewnama.getText();
        String vjurusan      = tfviewjurusan.getText();
        String vmtk      = tfmtk.getText();
        String vbhsindo  = tfbindonesia.getText();
        String vbhsing   = tfbinggris.getText();
        String vjumlah   = tfjumlah.getText();
        String vrata     = tfrata.getText();
        String vket      = tfketerangan.getText();
        if (tfidnilai.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Data Masih Kosong",
                "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                java.sql.Statement stat=conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT * FROM tblnilai WHERE ID_Nilai='"+tfidnilai.getText()+"'");
                if (data.next()){
                    JOptionPane.showMessageDialog(null,"ID Nilai sudah dimasukkan");
                    tfidnilai.requestFocus();
                }
                else {
                    String sql = "INSERT INTO tblnilai VALUES('"+vidn+"','"+vidk+"','"+vnama+"','"+vjurusan+"','"+vmtk+"','"+vbhsindo+"','"+vbhsing+"','"+vjumlah+"','"+vrata+"','"+vket+"')";
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"data telah tersimpan");
                    tfidnilai.setText("");
                    tfidkartu.setText("");
                    //cbidsiswa.setText("");
                    tfviewnama.setText("");
                    tfviewjurusan.setText("");
                    tfmtk.setText("");
                    tfbindonesia.setText("");
                    tfbinggris.setText("");
                    tfjumlah.setText("");
                    tfrata.setText("");
                    tfketerangan.setText("");
                    tfidnilai.requestFocus();
                }
                nomoran();
                //cbidsiswa();
                stat.close();
            }
        
            catch (Exception exc){
                System.err.println("Terjadi Kesalahan :"+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tblsave1ActionPerformed

    private void tfviewnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfviewnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfviewnamaActionPerformed

    private void tbldelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbldelete1ActionPerformed
        // TODO add your handling code here:
          String sql="delete from tblnilai where ID_Nilai='"+tfidnilai.getText().trim()+"'";
        if(tfidnilai.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "kode masih kosong !","Hapus Data",JOptionPane.WARNING_MESSAGE);
            tfidnilai.requestFocus();
        }
        else
        {
            try
            {
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data sudah dihapus","Hapus Data",JOptionPane.WARNING_MESSAGE);
                stat.close();
                tfidnilai.setText("");
                tfidkartu.setText("");
                tfviewnama.setText("");
                tfviewjurusan.setText("");
                tfmtk.setText("");
                tfbindonesia.setText("");
                tfbinggris.setText("");
                tfjumlah.setText("");
                tfrata.setText("");
                tfketerangan.setText("");
                tfidnilai.requestFocus();

                //nomoran();
            }
            catch(Exception exc)
            {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
        tabs();
    }//GEN-LAST:event_tbldelete1ActionPerformed

    private void tblcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tblcancel1ActionPerformed

    private void tblprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblprosesActionPerformed
        // TODO add your handling code here:
        int jumlah;
        int rata;
        int a = Integer.parseInt(tfmtk.getText());
        int b = Integer.parseInt(tfbindonesia.getText());
        int c = Integer.parseInt(tfbinggris.getText());
        
        jumlah = a+b+c;
        tfjumlah.setText(Integer.toString(jumlah));
        rata = (jumlah)/3;
        tfrata.setText(Integer.toString(rata));
        
        if(rata >= 60){
            tfketerangan.setText("Lulus");
        } else {
            tfketerangan.setText("Gagal");
        }
    }//GEN-LAST:event_tblprosesActionPerformed

    private void tfmtkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfmtkFocusLost
        int a = Integer.parseInt(tfmtk.getText());
        if(a >= 60){
            tfviewmtk.setText("Lulus");
        } else {
            tfviewmtk.setText("Gagal");
        }
    }//GEN-LAST:event_tfmtkFocusLost

    private void tfbindonesiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfbindonesiaFocusLost
        int b = Integer.parseInt(tfbindonesia.getText());
        if(b >= 60){
            tfviewbindonesia.setText("Lulus");
        } else {
            tfviewbindonesia.setText("Gagal");
        }
    }//GEN-LAST:event_tfbindonesiaFocusLost

    private void tfbinggrisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfbinggrisFocusLost
        int c = Integer.parseInt(tfbinggris.getText());
        if(c >= 60){
            tfviewbinggris.setText("Lulus");
        } else {
            tfviewbinggris.setText("Gagal");
        }
    }//GEN-LAST:event_tfbinggrisFocusLost

    private void tblsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsearchActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM tblnilai WHERE ID_Nilai='"+tfidnilai.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfidkartu.setText(rs.getString(2));
                tfmtk.setText(rs.getString(3));
                tfbindonesia.setText(rs.getString(4));
                tfbinggris.setText(rs.getString(5));
                tfjumlah.setText(rs.getString(6));
                tfrata.setText(rs.getString(7));
                tfketerangan.setText(rs.getString(8));
                String vid_kartu = tfidkartu.getText();
                String sql2 = "SELECT tblpendaftar.Nama_Lengkap,tblpendaftar.Jurusan FROM tblkartu,tblpendaftar WHERE tblkartu.ID_Pendaftar=tblpendaftar.ID_Pendaftar and tblkartu.ID_Kartu='"+vid_kartu+"'";
                try{
                    Statement stat2=conec.createStatement();
                    ResultSet rs2=stat2.executeQuery(sql2);
                    if(rs2.next())
                        
                    {
                        tfviewnama.setText(rs2.getString(1));
                        tfviewjurusan.setText(rs2.getString(2));
                    }
                }
                catch(Exception exc){
                System.err.println("Terjadi kesalahan : "+exc);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
               tfidnilai.requestFocus();
            }
          stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }

    }//GEN-LAST:event_tblsearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tfbinggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbinggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbinggrisActionPerformed

    private void tfbindonesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbindonesiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbindonesiaActionPerformed

    private void tfketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfketeranganActionPerformed

    private void tfidkartuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidkartuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            aaActionPerformed(new ActionEvent(evt.getSource(),evt.getID(),"KEY PRESS PROCESS"));
        }
    }//GEN-LAST:event_tfidkartuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai_hasil_tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai_hasil_tes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tblcancel1;
    private javax.swing.JButton tbldelete1;
    private javax.swing.JButton tbledit1;
    private javax.swing.JTable tblnilai;
    private javax.swing.JButton tblproses;
    private javax.swing.JButton tblsave1;
    private javax.swing.JButton tblsearch;
    private javax.swing.JTextField tfbindonesia;
    private javax.swing.JTextField tfbinggris;
    private javax.swing.JTextField tfidkartu;
    private javax.swing.JTextField tfidnilai;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfketerangan;
    private javax.swing.JTextField tfmtk;
    private javax.swing.JTextField tfrata;
    private javax.swing.JTextField tfviewbindonesia;
    private javax.swing.JTextField tfviewbinggris;
    private javax.swing.JTextField tfviewjurusan;
    private javax.swing.JTextField tfviewmtk;
    private javax.swing.JTextField tfviewnama;
    // End of variables declaration//GEN-END:variables

    private void koneksiDatabase() {
        //throw new UnsupportedOperationException("Not yet implemented");
        try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/sistempendaftaran","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
    
    }
    
        private void nomoran() {
        //throw new UnsupportedOperationException("Not yet implemented");
                String sql = "select right (ID_Nilai,3) as no from tblnilai order by ID_Nilai asc";
        
        try {
            Statement pst = conec.prepareStatement(sql);
            Statement stat = conec.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            if (rs.first()==false)
            {
                tfidnilai.setText("N001");
            }
            else {
                rs.last();
                int no = rs.getInt(1)+1;
                String kbinasi = String.valueOf(no);
                int pjg_kbinasi = kbinasi.length();
                String jebot = "";
                for(int i=0; i<3-pjg_kbinasi;i++){
                   // kbinasi = "0"+kbinasi;
                    jebot = jebot+"0";
                }
                tfidnilai.setText("N"+jebot+kbinasi);
            }
            rs.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan:"+e);

        }
        }

    private void aaActionPerformed(ActionEvent actionEvent) {
        String sql = "SELECT * FROM tblkartu WHERE ID_Kartu='"+tfidkartu.getText()+"'";
        try{
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next())
            {
                tfviewnama.setText(rs.getString(3));
                tfviewjurusan.setText(rs.getString(4));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "kode tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                tfmtk.requestFocus();
            }
            stat.close();
        }
        catch(Exception exc){
            System.err.println("Terjadi kesalahan : "+exc);
        }
    }
}
